# Generated by Django 2.1.4 on 2019-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encry_date', models.DateTimeField(verbose_name='date encrypted')),
                ('encry_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
